package ui.payments;

import net.serenitybdd.screenplay.targets.Target;
import org.openqa.selenium.By;

public class PaymentPage {
private PaymentPage(){}

    public static final String OPT_OWN_PRODUCTS = "#item_0";
    public static final String OPT_ENROLLED_PRODUCTS = "#item_1";
    public static final String OPT_FIRST_ELEMENT = "#card-list-0";
    public static final String OPT_SECOND_ELEMENT = "#card-list-1";
    public static final String OPT_THIRD_ELEMENT = "#card-list-2";
    public static final String TITLE_PRODUCT_DETAIL_ELEMENT_PAYMENT = "label.bdb-ml-content-title__left__content__title";
    public static final String TXT_PRODUCT_DETAIL_ELEMENT_PAYMENT = "label.bdb-ml-content-title__left__content__text";
    public static final Target LBL_HEADER_ACCORDION_ADVANCE = Target.the("Label header menú accordion advance").located(By.xpath("//*[contains(text(),'Detalle del avance')]"));
    public static final String TITLE_PRODUCT_DETAIL_HOST_PAYMENT = "bdb-ml-content-title";
    public static final String LBL_PRODUCT_NUMBER_SP = "#card-list-0 > div.bdb-ml-card-list__main-content > div > div > div.bdb-ml-card-list__main-content__header__detail__description";
    public static final String LBL_PRODUCT_NUMBER_CR = "#card-list-0 > div.bdb-ml-card-list__main-content > div > div > div:nth-child(2)";
    public static final Target LBL_HEADER_ACCORDION = Target.the("Label header menú accordion").located(By.cssSelector("bdb-transfers-list > ion-content bdb-header > header > div > div"));
    public static final Target LBL_HEADER_ACCORDION_PAYMENTS = Target.the("Label header menú Pagos").located(By.cssSelector("bdb-payments .bdb-header .bdb-header__title"));
    public static final Target LBL_HEADER_DETAIL = Target.the("Label detalle de Pagos").located(By.cssSelector("bdb-payment-detail .bdb-header"));
    public static final Target OPT_TC_ACCORDION = Target.the("Selecciona opción Tarjeta Crédito").locatedBy("#bdb-grid-item-0");
    public static final Target OPT_CREDIT_ACCORDION = Target.the("Selecciona opción Crédito").locatedBy("#bdb-grid-item-1");
    public static final Target OPT_SERVICES_ACCORDION = Target.the("Selecciona opción Servicios").locatedBy("#bdb-grid-item-3");
    public static final Target LBL_CREDIT_PRODUCT_NUMBER_DETAIL = Target.the("Label del número crédito en detalle de pago").locatedBy("#payment_detail_product_number");
    public static final Target LBL_CREDIT_PRODUCT_NUMBER_DETAIL_LIBRANZA = Target.the("Label del número crédito en detalle de pago").located(By.cssSelector(".payment-detail__payment-header__other__number"));
    public static final Target LBL_TC_PRODUCT_NUMBER_DETAIL = Target.the("Label del número tarjeta crédito en detalle de pago").located(By.cssSelector(".payment-detail .payment-detail__payment-header__business__number"));
    public static final Target PAYMENTPRODUCT_LIST = Target.the("Lista de productos disponibles para pagos").located(By.cssSelector(".bdb-item-payment__payment-type__content__label.ng-star-inserted"));
    public static final Target VALUE_SERVICES = Target.the("Ingresar Valor servicio").locatedBy("#payment_detail_amount_input");
    public static final Target CONGRATULATIONS_MESSAGE_TC = Target.the("Felicitaciones tu TC no tiene deuda").locatedBy("#alert_success_title");
    public static final Target OTHER_VALUE = Target.the("Pagar otro valor").locatedBy("#radio_payment-detail_2 .bdb-radio__content__box__circle");
    public static final Target MINIMUM_PAY = Target.the("Valor pago mínimo").located(By.cssSelector("#radio_payment-detail_0 .bdb-radio__content__box__circle"));
    public static final Target PMA_PAY = Target.the("Valor pago mínimo alterno").locatedBy("#radio_payment-detail_4 .bdb-radio__content__box__circle");
    public static final Target PT_PAY = Target.the("Valor pago total").locatedBy("//*[@id='radio_payment-detail_1']/div/div[1]");
    public static final Target FULL_PAYMENT = Target.the("Valor pago total").locatedBy("#radio_payment-detail_1");
    public static final Target INPUT_AMOUNT = Target.the("Ingresar Valor").locatedBy("#payment_detail_amount_input");
    public static final Target PAY_BUTTON = Target.the("Botón Pagar").located(By.xpath("//*[contains(text(),'Pagar')]"));
    public static final String FIRST_OPTION_MENU = "#menu_0";
    public static final String DOTS_OPTION_MENU = "#overflow-menu_0_ico";
    public static final String OPT_DELETE_PRODUCT = "#item_1 > div.bdb-overflow-menu__content__box__options__item__label";
    public static final Target LST_SELECTOR = Target.the("Dropdown de los tipos de crédito").locatedBy("#payment_detail_select\\.payment\\.type_selectpicker > div > div:nth-child(2)");
    public static final Target OPT_TYPE_ONE = Target.the("Opción uno de tipo de crédito").locatedBy("#item__0");
    public static final Target OPT_TYPE_TWO = Target.the("Opción dos de tipo de crédito").locatedBy("#item__1");
    public static final Target OPT_TYPE_THREE = Target.the("Opción tres de tipo de crédito").locatedBy("#item__2");
    public static final String OPT_SHADOW_TC = "#radio_payment-detail_4 > div.bdb-radio__content__input.ng-star-inserted > div > bdb-at-alert > div > bdb-at-check-button";
    public static final String LINK_TC = "#payment_detail_show\\\\.terms\\\\.and\\\\.conditions_button_pma";
    public static final Target TXT_TYC = Target.the("Texto términos y condiciones").locatedBy("/html/body/app-root/ion-app/ion-router-outlet/bdb-pma-terms/ion-content/div[1]/div/div[1]");
    public static final Target BACK = Target.the("Botón regresar de T&C y pantalla confirmación").locatedBy("#header-back");
    public static final Target CLOSE = Target.the("Botón cerrar de T&C y pantalla confirmación").locatedBy("#header-close");
    public static final Target ACCEPT_TYC = Target.the("Botón aceptar T&C").locatedBy("/html/body/app-root/ion-app/ion-router-outlet/bdb-pma-terms/ion-content/div[2]/button");

    public static final Target BTN_CONTINUE = Target.the("Botón continuar").locatedBy("//*[@id='payment_detail_btn.pay_button']");
    public static final String OPT_PMA_PM_PT = "body > app-root > ion-app > ion-router-outlet > bdb-transaction-confirmation > ion-content > div > div.bdb-trx-confirmation > bdb-ml-confirmation";
    public static final Target VALUE_PMA = Target.the("Valor de PMA").locatedBy("//*[@id='radio_payment-detail_4']/div/div[3]");
    public static final String LBL_COPYS = "#bdb-ml-confirmation > div.bdb-ml-confirmation__content > div:nth-child(2) > div:nth-child(2) > div.bdb-ml-confirmation__content__section__content__title > label";
    public static final Target BANNER_TYC = Target.the("Banner términos y condiciones").locatedBy("//*[@id='radio_payment-detail_4']/div[2]/div/bdb-at-alert/div/div");
    public static final Target BANNER_TYC_OV = Target.the("Banner términos y condiciones otro valor").locatedBy("//*[@id='radio_payment-detail_2']/div[3]/div/bdb-at-alert/div/div");
    public static final String LBL_NUM_TC = "#bdb-ml-confirmation > div.bdb-ml-confirmation__content > div:nth-child(1) > div:nth-child(2) > div.bdb-ml-confirmation__content__section__content__value > label";
    public static final String LBL_CA = "#bdb-ml-confirmation > div.bdb-ml-confirmation__content > div:nth-child(3) > div:nth-child(2) > div.bdb-ml-confirmation__content__section__content__value > label";
    public static final String LBL_CHECK_INFORMATION = "#warning_trx_confirmation > bdb-at-alert";
    public static final String LBL_INFORMATION = "#bdb-at-alert > div > slot > div";
    public static final String CHECK_TYC = ".bdb-at-checkbox__content__square--check";
    public static final String CHECK_TYC_OV = "#bdb-at-check-button";
    public static final String VALUE_PMA_PM_PT_CONFIRMATION = "#bdb-ml-confirmation > div.bdb-ml-confirmation__content > div:nth-child(2) > div:nth-child(1) > div.bdb-ml-confirmation__content__section__content__value.bdb-ml-confirmation__content__section__content__value--bold > div";
    public static final Target ALERT_QUESTION_CLOSE = Target.the("Pregunta de alerta al cerrar en pantalla confirmación").locatedBy("#bdb-confirmation-title-CREDIT_CARD_EXIT_CONFIRMATION");
    public static final Target ALERT_DESCRIPTION_CLOSE = Target.the("Descripción de alerta al cerrar en pantalla confirmación").locatedBy("#bdb-confirmation-description-CREDIT_CARD_EXIT_CONFIRMATION");
    public static final Target BTN_NO_EXIT = Target.the("Botón No continuar").locatedBy("#bdb-confirmation-cancel-CREDIT_CARD_EXIT_CONFIRMATION");
    public static final Target BTN_YES_EXIT = Target.the("Botón Si continuar").locatedBy("#bdb-confirmation-ok-CREDIT_CARD_EXIT_CONFIRMATION");
    public static final Target LBL_PRODUCTS = Target.the("Label Products Dashboard").locatedBy(".card-products__header__title");
    public static final String LINK_CHANGE = "#bdb-ml-confirmation > div.bdb-ml-confirmation__title > button";
    public static final Target INPUT_EMAIL = Target.the("Input Email").locatedBy("bdb-email__box ng-untouched ng-pristine ng-valid ng-star-inserted");
    public static final Target REMOVE_EMAIL = Target.the("Equis para remover el  Email").locatedBy("#email_credit_card_payment_email.confirmation_input_0_remove");
    public static final Target ALERT_EMAIL = Target.the("Alertta que aparece cuando el correo esta mal escrito").locatedBy(".bdb-email__label__error ng-star-inserted");
    public static final Target PAY = Target.the("Alerta que aparece cuando el correo esta mal escrito").locatedBy("#credit_card_payment_send.confirmation_button");
    public static final String OPT_SHADOW_TC_OV = "#radio_payment-detail_2 > div:nth-child(3) > div > bdb-at-alert > div > bdb-at-check-button";
    public static final String LINK_TC_OV = "#payment_detail_show\\\\.terms\\\\.and\\\\.conditions_button";
    public static final String OPT_SHADOW_TSX = "#new_voucher > div > bdb-ml-bm-voucher";
    public static final String LBL_SUCCESSFUL_TSX = "#creditcardpayment_voucher_button > div > div.voucher__header > div:nth-child(1) > div.voucher__header__title > div.voucher__header__title__label";
    public static final String LBL_FAILED_TSX = "#creditcardpayment_voucher_button > div > div.voucher__header > div:nth-child(1) > div.voucher__header__title > div";

    public static final String LBL_VALUE_TSX = "#creditcardpayment_voucher_button > div > div.voucher__body > div.voucher__body__box.voucher__body__box--success > div.voucher__body__box__value > div.voucher__body__box__value__amount";
    public static final String LBL_VALUE_FAILED_TSX = "#creditcardpayment_voucher_button > div > div.voucher__body > div.voucher__body__box.voucher__body__box--fail > div.voucher__body__box__value > div.voucher__body__box__value__amount";
    public static final Target LBL_TC_TSX = Target.the("N° de TC en Vaucher").locatedBy("//*[@id='new_voucher']/div/bdb-ml-bm-voucher/div[1]/div[3]/div[2]");
    public static final Target LBL_CC_TSX = Target.the("LBL Número de cuenta corriente").locatedBy("//*[@id='new_voucher']/div/bdb-ml-bm-voucher/div[2]/div/div[2]");
    public static final String BTN_NEW_PAY = "#creditcardpayment_voucher_button__transfer";
    public static final Target LBL_BACK_PAY = Target.the("LBL regresar a pagos").locatedBy("//*[@id='page_payments_content']/div/div[1]");
    public static final Target LBL_PM = Target.the("LBL PM").locatedBy("//*[@id='radio_payment-detail_0']/div/div[3]");
    public static final Target LBL_PMA = Target.the("LBL PMA").locatedBy("//*[@id='radio_payment-detail_4']/div/div[3]");
    public static final Target LBL_PT = Target.the("LBL PT").locatedBy("//*[@id='radio_payment-detail_1']/div/div[3]");
    public static final Target LIST_ACCOUNT = Target.the("Lista de cuentas usuario multicuenta").locatedBy("#select_account_");
    public static final Target ACCOUNT_TWO = Target.the("Seleccion de cuenta # 2").locatedBy("#account__1");
    public static final Target ACCOUNT_FOUR = Target.the("Seleccion de cuenta # 4").locatedBy("#account__3");
    public static final Target ACCOUNT_SIX = Target.the("Seleccion de cuenta # 6").locatedBy("#account__5");
    public static final String BTN_PAYMENT = "#credit_card_payment_send\\\\.confirmation_button";
    public static final Target DUPLICATE_VALUE_ALERT= Target.the("Cuando se ha realizado una tsx por el mismo valor sale una alerta, seleccion SI ").locatedBy(" #bdb-confirmation-ok-DUPLICATE_PAYMENT_CREDIT_ERROR");
    public static final Target ALERT_FAILED_VOUCHER = Target.the("Btn continuar de alerta del servicio fallido ").locatedBy("#alert_warning_btn");
    public static final String FAILED_TSX = "#creditcardpayment_voucher_button > div > div.voucher__header > div:nth-child(1) > div.voucher__header__description";
    public static final String VALUE =  "#creditcardpayment_voucher_button > div > div.voucher__body > div.voucher__body__box.voucher__body__box--fail > div.voucher__body__box__value > div.voucher__body__box__value__amount";
}

