
serenity.project.name = Demo Project using Appium, Serenity Screenplay and Cucumber

webdriver.driver= appium
appium.hub = http://localhost:4723/wd/hub

####### Android CAPS ######
appium.automationName=uiautomator2
appium.platformName = Android
appium.platformVersion = 15.0
appium.deviceName  = AutomationTesting
#appium.app = D:\\serenitybdd-appium-poc\\src\\test\\resources\\TheApp-v1.10.0.apk
appium.newCommandTimeout = 1000