name: Expresiones
run-name: ¡Estoy aprendiendo a usar Expresiones!

on:
  push:
    branches:
      - pruebas-pr

  workflow_dispatch:

    inputs:
      edad:
        description: 'Edad'
        required: true
        default: 30
        type: integer
      name:
        description: 'Nombre'
        required: true
        default: 'Manuel'
        type: string

  env:
    EDAD: ${{ inputs.edad}}
    NOMBRE: ${{ inputs.name || 'Manuel' }}

jobs:

  mayor:
    if: ${{ inputs.EDAD >= 18 }}
    runs-on: ubuntu-latest

    steps:
      - name: Correr script
        run: echo "${{ inputs.Nombre }} es mayor de edad"

  menor:
    if: ${{ inputs.EDAD < 18 }}
    runs-on: ubuntu-latest

    steps:
      - name: Correr script
        run: echo "${{ inputs.Nombre }} es menor de edad"