name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV 
      - name: Correr script
        run: java hola-mundo.java


name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compilar
        run: javac hola-mundo.java

      - name: Ejecutar
        run: java hola-mundo
