name: Aprendiendo GitHub Actions

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ver estructura
        run: ls -R

      - name: Compilar
        run: javac src/HolaMundo.java

      - name: Ejecutar
        run: java -cp src HolaMundo
