name: automated-testing-integration

on:
  push:
    branches:
      - staging
      - master
      - Feature/*
  workflow_dispatch:

jobs:

  integration-security-tests:
    uses: bancodebogota/bbog-dig-do-testing-pipeline/.github/workflows/test_security_integration.yml@feature/fix-mobsf
    with:
      prefix-team: 'BM'
      environment: st_pipeline
      release-id-steward: ${{ inputs.release_id }}
      repository: 'bbog-bm-automated-testing'
      path-app: 'app/app-release-10-23-0.apk'
    secrets:
        DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}